services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: tfc
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
